all: SicAssembler.class HashTable.class OPCode.class DataItem.class Assembler.class OPHashTable.class
SicAssembler.class: SicAssembler.java
	javac SicAssembler.java
HashTable.class: HashTable.java
	javac HashTable.java
OPCode.class: OPCode.java
	javac OPCode.java
DataItem.class: DataItem.java
	javac DataItem.java
Assembler.class: Assembler.java
	javac Assembler.java
OPHashTable.class: OPHashTable.java
	javac OPHashTable.java